# Generated by Django 3.1.7 on 2021-04-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('review', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='comments',
            field=models.ManyToManyField(to='comment.Comment'),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='reviews',
            field=models.ManyToManyField(to='review.Review'),
        ),
    ]
