# Generated by Django 3.1.7 on 2021-04-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_touristattraction_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='minimal_age',
            field=models.IntegerField(blank=True),
        ),
    ]
