# Generated by Django 3.1.7 on 2021-04-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20210405_1717'),
        ('core', '0004_auto_20210405_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.addres'),
        ),
    ]
