# Generated by Django 3.1.7 on 2021-04-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210405_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_attractions'),
        ),
    ]
