# Generated by Django 3.1.7 on 2021-04-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Addres',
        ),
    ]
