# Generated by Django 3.1.7 on 2021-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20210405_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='latitude',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addres',
            name='longitude',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
