# Generated by Django 3.1.7 on 2021-04-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20210405_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addres',
            name='line2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='addres',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
